import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import AuthenticationGuard from './_components/AuthenticationGuard';
import Navbar from './_components/Navbar';
import { isAuthenticationEnabled } from '@/lib/services/auth';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const serverUrl = process.env.SERVER_URL;
  const tokenUrl = process.env.TOKEN_URL;
  const isAuthEnabled = isAuthenticationEnabled(serverUrl, tokenUrl);
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} dark h-full antialiased`}
      data-theme="dark"
      suppressHydrationWarning
    >
      <body className="flex min-h-full flex-col">
        <Navbar isAuthenticationEnabled={isAuthEnabled} />
        <AuthenticationGuard serverUrl={serverUrl} tokenUrl={tokenUrl}>
          {children}
        </AuthenticationGuard>
      </body>
    </html>
  );
}
