import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { THEME_KEY } from '../lib/utils/constants';
import './globals.css';
import AuthenticationGuard from './_components/AuthenticationGuard';
import Navbar from './_components/Navbar';
import { isNonEmptyString } from '@/lib/utils/strings';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const themeInitializer = `
  try {
    const storedTheme = localStorage.getItem(${JSON.stringify(THEME_KEY)});
    const theme = storedTheme === 'light' ? 'light' : 'dark';
    document.documentElement.classList.remove('light', 'dark');
    document.documentElement.classList.add(theme);
    document.documentElement.dataset.theme = theme;
  } catch {}
`;

export default function RootLayout({ children }: LayoutProps<'/'>) {
  const serverUrl = process.env.SERVER_URL;
  const tokenUrl = process.env.TOKEN_URL;
  const isAuthEnabled = isNonEmptyString(serverUrl) && isNonEmptyString(tokenUrl);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} dark h-full antialiased`}
      data-theme="dark"
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitializer }} />
      </head>
      <body className="flex min-h-full flex-col">
        <Navbar isAuthenticationEnabled={isAuthEnabled} />
        <AuthenticationGuard serverUrl={serverUrl} tokenUrl={tokenUrl}>
          {children}
        </AuthenticationGuard>
      </body>
    </html>
  );
}
